### ISSUE TITLE
Configuration and predicates

### ISSUE THREAD

**Issue by ross-weir** [ChainCashLabs/chaincash-rs#4]
The `chaincash` application will have one configuration file to config all components (server, p2p, db, etc). Using TOML as that's pretty standard for rust apps and there's no HOCON support.

We will also ship common note acceptance predicate configs with the app that users can optionally edit to their liking.

So the app will ship something like the following directory tree, ignoring standardised XDG directories for now to give a better idea of chaincash config.

```
├── chaincash.exe
├── chaincash.toml
└── predicates
    └── whitelist_or_collaterized.toml
```

Where
- `chaincash.exe` is chaincash cli binary
- `chaincash.toml` is main config file
- `predicates/` is a directory containing note acceptance predicates config, this can come with supplied commonly used configs and users can also add their own configs or modify supplied configs
- `predicates/whitelist_or_collaterized.toml` is a popular predicate config shipped with `chaincash`, it accepts notes where the agent is either whitelisted or the note is collaterized

Example of possible `chaincash.toml` configuration:

```toml
[server]
# server/rest api config
host = "0.0.0.0"
port = 8080

[p2p]
# p2p config

[acceptance]
predicates = ["predicates/whitelist_or_collaterized.toml"] # list of enabled predicate configs, full path or relative to $CWD, if any predicates listed here return true the note is accepted
```

Example of possible predicate config, `whitelist_or_collaterized`:

```toml
type = "or"
conditions = [
  {type: "whitelist", agents: ["PK1", "PK2"]},
  {type: "collaterized", percent: 100}
]
```
